#1. Import the NUMPY package under the name np.


In [5]:
import numpy as np

#2. Print the NUMPY version and the configuration.



In [6]:
print(np.__version__)

1.20.2


#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
#Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?



In [7]:
# Method_1

a = np.random.random((2,3,5))

a

array([[[0.42198889, 0.50821952, 0.83515738, 0.76661526, 0.27515085],
        [0.03658686, 0.24392097, 0.2941045 , 0.20913978, 0.28157468],
        [0.317705  , 0.9692637 , 0.64713364, 0.96235169, 0.09644416]],

       [[0.10470082, 0.72538395, 0.71715531, 0.85791838, 0.2437644 ],
        [0.64386465, 0.29342529, 0.12556522, 0.06724587, 0.60079397],
        [0.30355141, 0.61288952, 0.47638457, 0.95632188, 0.98228356]]])

In [8]:
# Method_2

a = np.random.sample((2,3,5))

a

array([[[0.59032292, 0.9894972 , 0.75976039, 0.80800894, 0.09738938],
        [0.85259432, 0.17657565, 0.67189109, 0.48113621, 0.92753706],
        [0.06951464, 0.77046314, 0.97744839, 0.81569401, 0.49770263]],

       [[0.92077707, 0.00866543, 0.54892685, 0.25135529, 0.19628981],
        [0.81379307, 0.7646238 , 0.56674625, 0.68285856, 0.43013471],
        [0.73988965, 0.45584267, 0.74108524, 0.29925479, 0.32088672]]])

In [9]:
# Method_3

a = np.random.rand(2,3,5)

a

array([[[0.80526416, 0.31664708, 0.43133704, 0.74452685, 0.68045493],
        [0.52299074, 0.81790598, 0.08229111, 0.89851063, 0.92209031],
        [0.57777216, 0.33618776, 0.23604874, 0.0093078 , 0.66673994]],

       [[0.30383723, 0.74982735, 0.01762385, 0.44194133, 0.23535119],
        [0.96944397, 0.96738923, 0.40743328, 0.26350096, 0.8624581 ],
        [0.59206815, 0.80206881, 0.45160314, 0.33481377, 0.60271632]]])

#4. Print a.

In [10]:
print(a)

[[[0.80526416 0.31664708 0.43133704 0.74452685 0.68045493]
  [0.52299074 0.81790598 0.08229111 0.89851063 0.92209031]
  [0.57777216 0.33618776 0.23604874 0.0093078  0.66673994]]

 [[0.30383723 0.74982735 0.01762385 0.44194133 0.23535119]
  [0.96944397 0.96738923 0.40743328 0.26350096 0.8624581 ]
  [0.59206815 0.80206881 0.45160314 0.33481377 0.60271632]]]


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [11]:
b = np.ones((5,2,3))

b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#4. Print b.

In [12]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#7. Do a and b have the same size? How do you prove that in Python code?



In [13]:
if a.size == b.size:
    print("They are the same size")
else:
    print("They don't")

They are the same size


#8. Are you able to add a and b? Why or why not?

In [14]:
print("No, because even tho they have the same size, the shapes are different.")
# c = a+b

No, because even tho they have the same size, the shapes are different.


#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [15]:
c = np.transpose(b, axes=(1,2,0))
c.shape

(2, 3, 5)

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [16]:
d = a + c

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.



In [23]:
print(a[0])

[[0.80526416 0.31664708 0.43133704 0.74452685 0.68045493]
 [0.52299074 0.81790598 0.08229111 0.89851063 0.92209031]
 [0.57777216 0.33618776 0.23604874 0.0093078  0.66673994]]


In [24]:

print(d[0])

[[1.80526416 1.31664708 1.43133704 1.74452685 1.68045493]
 [1.52299074 1.81790598 1.08229111 1.89851063 1.92209031]
 [1.57777216 1.33618776 1.23604874 1.0093078  1.66673994]]


In [ ]:
#The only difference that I notice is we just add 1 

#12. Multiply a and c. Assign the result to e.



In [25]:
e = a * c
print(e)

[[[0.80526416 0.31664708 0.43133704 0.74452685 0.68045493]
  [0.52299074 0.81790598 0.08229111 0.89851063 0.92209031]
  [0.57777216 0.33618776 0.23604874 0.0093078  0.66673994]]

 [[0.30383723 0.74982735 0.01762385 0.44194133 0.23535119]
  [0.96944397 0.96738923 0.40743328 0.26350096 0.8624581 ]
  [0.59206815 0.80206881 0.45160314 0.33481377 0.60271632]]]


#13. Does e equal to a? Why or why not?



In [26]:
if np.array_equal(e,a):
    print("Yes they´re equal")
    
# C is the transpose of b who is only ones, so we`re just multiplying "a" by 1

Yes they´re equal


#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [27]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.9694439744709313
1.0093078018241004
1.535005063547836


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.



In [28]:
f = np.empty([2,3,5])


## 16. Populate the values in f. 

For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.




In [29]:
f = []
for x in np.nditer(d):
    if d_min < x < d_mean:
        f += [25]
    if d_mean < x < d_max:
        f += [75]
    if x == d_mean:
        f += [50]
    if x == d_min:
        f += [0]
    if x == d_max:
        f += [100]
    
        
f = np.reshape(f, d.shape) 
print(f)


[[[ 75  25  25  75  75]
  [ 25  75  25  75  75]
  [ 75  25  25   0  75]]

 [[ 25  75  25  25  25]
  [100  75  25  25  75]
  [ 75  75  25  25  75]]]


In [ ]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""



In [30]:
print(d)
print(f)

[[[1.80526416 1.31664708 1.43133704 1.74452685 1.68045493]
  [1.52299074 1.81790598 1.08229111 1.89851063 1.92209031]
  [1.57777216 1.33618776 1.23604874 1.0093078  1.66673994]]

 [[1.30383723 1.74982735 1.01762385 1.44194133 1.23535119]
  [1.96944397 1.96738923 1.40743328 1.26350096 1.8624581 ]
  [1.59206815 1.80206881 1.45160314 1.33481377 1.60271632]]]
[[[ 75  25  25  75  75]
  [ 25  75  25  75  75]
  [ 75  25  25   0  75]]

 [[ 25  75  25  25  25]
  [100  75  25  25  75]
  [ 75  75  25  25  75]]]


In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

In [31]:
j = []
for x in np.nditer(d):
    if d_min < x < d_mean:
        j += ['B']
    if d_mean < x < d_max:
        j += ['D']
    if x == d_mean:
        j += ['C']
    if x == d_min:
        j += ['A']
    if x == d_max:
        j += ['E']
    
j = np.reshape(j, d.shape) 
print(j)

[[['D' 'B' 'B' 'D' 'D']
  ['B' 'D' 'B' 'D' 'D']
  ['D' 'B' 'B' 'A' 'D']]

 [['B' 'D' 'B' 'B' 'B']
  ['E' 'D' 'B' 'B' 'D']
  ['D' 'D' 'B' 'B' 'D']]]
